import type { Entry } from "@/types/entry";

export const entries: Entry[] = [
  {
    gameId: "1",
    abbreviation: "DIY",
    answer: "Do It Yourself",
    abbreviationType: "initialism",
    category: "common",
  },
  {
    gameId: "2",
    abbreviation: "CPU",
    answer: "Central Processing Unit",
    abbreviationType: "initialism",
    category: "tech",
  },
  {
    gameId: "3",
    abbreviation: "FBI",
    answer: "Federal Bureau of Investigation",
    abbreviationType: "initialism",
    category: "organizations",
  },
  {
    gameId: "4",
    abbreviation: "NASA",
    answer: "National Aeronautics and Space Administration",
    abbreviationType: "acronym",
    category: "organizations",
  },
  {
    gameId: "5",
    abbreviation: "CEO",
    answer: "Chief Executive Officer",
    abbreviationType: "initialism",
    category: "business",
  },
  {
    gameId: "6",
    abbreviation: "ATM",
    answer: "Automated Teller Machine",
    abbreviationType: "initialism",
    category: "tech",
  },
  {
    gameId: "7",
    abbreviation: "MRI",
    answer: "Magnetic Resonance Imaging",
    abbreviationType: "initialism",
    category: "science",
  },
  {
    gameId: "8",
    abbreviation: "GIF",
    answer: "Graphics Interchange Format",
    abbreviationType: "acronym",
    category: "tech",
  },
  {
    gameId: "9",
    abbreviation: "FAQ",
    answer: "Frequently Asked Questions",
    abbreviationType: "initialism",
    category: "common",
  },
  {
    gameId: "10",
    abbreviation: "NBA",
    answer: "National Basketball Association",
    abbreviationType: "initialism",
    category: "sports",
  },
  {
    gameId: "11",
    abbreviation: "IMO",
    answer: "In My Opinion",
    abbreviationType: "initialism",
    category: "slang",
  },
  {
    gameId: "12",
    abbreviation: "EPL",
    answer: "English Premier League",
    abbreviationType: "initialism",
    category: "sports",
  },
];
