import type { Entry } from "@/types/entry";

export const entries: Entry[] = [
  {
    gameId: "1",
    abbreviation: "DIY",
    answer: "Do It Yourself",
    abbreviationType: "initialism",
    category: "common",
  },
  {
    gameId: "2",
    abbreviation: "CPU",
    answer: "Central Processing Unit",
    abbreviationType: "initialism",
    category: "tech",
  },
  {
    gameId: "3",
    abbreviation: "FBI",
    answer: "Federal Bureau of Investigation",
    abbreviationType: "initialism",
    category: "organizations",
  },
  {
    gameId: "4",
    abbreviation: "NASA",
    answer: "National Aeronautics and Space Administration",
    abbreviationType: "acronym",
    category: "organizations",
  },
  {
    gameId: "5",
    abbreviation: "CEO",
    answer: "Chief Executive Officer",
    abbreviationType: "initialism",
    category: "business",
  },
  {
    gameId: "6",
    abbreviation: "ATM",
    answer: "Automated Teller Machine",
    abbreviationType: "initialism",
    category: "tech",
  },
  {
    gameId: "7",
    abbreviation: "MRI",
    answer: "Magnetic Resonance Imaging",
    abbreviationType: "initialism",
    category: "science",
  },
  {
    gameId: "8",
    abbreviation: "GIF",
    answer: "Graphics Interchange Format",
    abbreviationType: "acronym",
    category: "tech",
  },
  {
    gameId: "9",
    abbreviation: "FAQ",
    answer: "Frequently Asked Questions",
    abbreviationType: "initialism",
    category: "common",
  },
  {
    gameId: "10",
    abbreviation: "NBA",
    answer: "National Basketball Association",
    abbreviationType: "initialism",
    category: "sports",
  },
  {
    gameId: "11",
    abbreviation: "IMO",
    answer: "In My Opinion",
    abbreviationType: "initialism",
    category: "slang",
  },
  {
    gameId: "12",
    abbreviation: "EPL",
    answer: "English Premier League",
    abbreviationType: "initialism",
    category: "sports",
  },
  {
    gameId: "13",
    abbreviation: "WHO",
    answer: "World Health Organization",
    abbreviationType: "initialism",
    category: "organizations",
  },
  {
    gameId: "14",
    abbreviation: "TA",
    answer: "Teaching Assistant",
    abbreviationType: "initialism",
    category: "education",
  },
  {
    gameId: "15",
    abbreviation: "NATO",
    answer: "North Atlantic Treaty Organization",
    abbreviationType: "acronym",
    category: "organizations",
  },
  {
    gameId: "16",
    abbreviation: "AFK",
    answer: "Away From Keyboard",
    abbreviationType: "initialism",
    category: "common",
  },
  {
    gameId: "17",
    abbreviation: "EU",
    answer: "European Union",
    abbreviationType: "initialism",
    category: "organizations",
  },
  {
    gameId: "18",
    abbreviation: "ETA",
    answer: "Estimated Time of Arrival",
    abbreviationType: "initialism",
    category: "common",
  },
  {
    gameId: "19",
    abbreviation: "2FA",
    answer: "Two-Factor Authentication",
    abbreviationType: "initialism",
    category: "tech",
  },
  {
    gameId: "20",
    abbreviation: "PDF",
    answer: "Portable Document Format",
    abbreviationType: "initialism",
    category: "tech",
  },
];
