import type { Metadata } from "next";
import { DM_Mono, Cabin } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "next-themes";

const cabinSans = Cabin({
  variable: "--font-cabin-sans",
  subsets: ["latin"],
  weight: "400",
});

const cabinSerif = Cabin({
  variable: "--font-cabin-serif",
  subsets: ["latin"],
  weight: "700",
});

const dmMono = DM_Mono({
  variable: "--font-dm-mono",
  subsets: ["latin"],
  weight: "400",
});

export const metadata: Metadata = {
  title: "initialism",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${cabinSans.variable} ${cabinSerif.variable} ${dmMono.variable} antialiased`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
